const SERVER_ERRORS = {
  TOO_MANY_REQUESTS: 0,
  USER_NOT_FOUND: 1,
  USER_EXISTS_ALREADY: 1,
  PRODUCT_NOT_FOUND: 1,
  PRODUCT_INSUFFICIENT_STOCK: 1,
  ORDER_NOT_FOUND: 2,
  ORDER_WITH_NO_ITEMS: 2,
};
export default SERVER_ERRORS;
